### ISSUE TITLE
Teams Page

### ISSUE THREAD

**Issue by SoumyaRanjanPatnaik** [Student-Activity-Center-IIIT-NR/sac-website#37]
- [x] #38
- [x] #39
- [x] #40
- [ ] #41
- [x] #42

**Comment by gautamsarawagi** [comment]
I want to work on this page starting with the routing part.

**Comment by sudhanshu1309** [comment]
routing part will be done later after finalizing each subsection.

**Comment by gautamsarawagi** [comment]
okay so I can also start with the subsections too

**Comment by sudhanshu1309** [comment]
yes
